# Generated by Django 5.1.7 on 2025-03-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agriShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Fertilizer', 'Fertilizer'), ('Plants', 'Plants'), ('Seeds', 'Seeds')], max_length=50)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image', models.ImageField(upload_to='shop_images/')),
            ],
        ),
    ]
