# Generated by Django 5.1.7 on 2025-03-29 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantXpert', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='agriShop',
        ),
    ]
